### ISSUE TITLE
Funky error! Please help!

### ISSUE THREAD

**Issue by pandeyanujk** [learn-co-curriculum/javascript-strings-lab#47]
Using this line of code

var topic = `Let's talk about space`;

var conversation = `${topic}`;

Getting this error: 

 1)  interpolates a string in `conversation`:

      Error: Expected 'Let\'s talk about space' to equal 'Let\'s talk about Let\'s talk about space.'
      + expected - actual

      -Let's talk about space
      +Let's talk about Let's talk about space.

      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
      at Context.<anonymous> (test/index-test.js:12:24)

**Comment by charlene74** [comment]
I have the same error. Did anyone manage to figure it out?

**Comment by lauraroyle** [comment]
I am getting the same error and can't move forward. Is it something wrong with my code or a bug in the IDE? 

var greeting = "Hello, everybody!";

var specialGuest = "Neil deGrasse Tyson"

var greetSpecialGuest = "Hello, " + specialGuest + "!";

var topic = "Let\'s talk about space.";

var conversation = `${topic}`;

**Comment by aaongr** [comment]
Hello,

If you look at the [test file](https://github.com/learn-co-curriculum/javascript-strings-lab/blob/master/test/index-test.js) you will see what it tries to test:

```
it('interpolates a string in `conversation`', function() {
  expect(conversation).toEqual(`Let's talk about ${topic}.`)
})
```

So, if the `topic` is the `space`, the correct string is `Let's talk about space.`

The above code, maybe looks better like this:

```
var topic = "space";
var conversation = `Let's talk about ${topic}.`;
```
Please mind the period at the end...
